import diffusive_convective_heat_mass_transfer_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace diffusive_convective_heat_mass_transfer_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end diffusive_convective_heat_mass_transfer_theorem_canonical_lane_mathlib
end HautevilleHouse
